# Theano Tensor Indexing

In [ ]:
!pip install theano tensor

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.3/50.3 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 15.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 8.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 19.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.0/80.0 kB 11.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 29.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.6/74.6 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.3/247.3 kB 26.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 6.7 MB/s eta 0:00:00
  Created wheel for tensor: filename=tensor-0.3.6-py3-none-any.whl size=71552 sha256=83194cef82ba89b12d1a77e540ebc1a06bc84ccd1f0fc410cffc20570c9e9a76
  Stored in directory: /root/.cache/pip/wheels/b8/d7/e8/f4760f8bcef039fce5899d36f67a

In [ ]:
import theano
import theano.tensor as T
import numpy as np

In [ ]:
t = T.arange(9)

print t[1::2].eval()

[1 3 5 7]


In [ ]:
n = np.arange(9)

print n[1::2]

[1 3 5 7]


In [ ]:
t = T.arange(9).reshape((3,3))

print t[t > 4].eval()

[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [3 4 5]]

 [[3 4 5]
  [3 4 5]
  [3 4 5]]]


In [ ]:
n = np.arange(9).reshape((3,3))

print n[n > 4]

[5 6 7 8]


In [ ]:
print t[(t > 4).nonzero()].eval()

[5 6 7 8]


In [ ]:
r = T.vector()

new_r = T.set_subtensor(r[10:], 5)

### T.inc_subtensor(x, y)

In [ ]:
r = T.vector()

new_r = T.inc_subtensor(r[10:], 5)